# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-security-hub
  description: This component is responsible for configuring Security Hub within an AWS Organization
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








